version: "3.9"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resqwear_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./resqwear.sqlite:/app/resqwear.sqlite
    depends_on:
      - simulator

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.sim
    container_name: resqwear_simulator
    ports:
      - "8765:8765"
    volumes:
      - ./resqwear.sqlite:/app/resqwear.sqlite
